CREATE TABLE "GROUPS_DISH" (
	"ID" serial NOT NULL,
	"Name" varchar(255) NOT NULL,
	CONSTRAINT "GROUPS_DISH_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "DISH" (
	"ID" serial NOT NULL,
	"Name" varchar(255) NOT NULL,
	"Price" integer NOT NULL,
	"ID_group" integer NOT NULL,
	CONSTRAINT "DISH_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "ORDER_DISH" (
	"ID_order" integer NOT NULL,
	"ID_dish" integer NOT NULL,
	"Count" integer NOT NULL
) WITH (
  OIDS=FALSE
);



CREATE TABLE "ORDER" (
	"ID" serial NOT NULL,
	"Phone_client" varchar(255) NOT NULL,
	"ID_type" integer NOT NULL,
	"ID_point" integer NOT NULL,
	CONSTRAINT "ORDER_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "TYPE_DELIVERY" (
	"ID" serial NOT NULL,
	"Name" varchar(255) NOT NULL,
	CONSTRAINT "TYPE_DELIVERY_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "FEEDBACK" (
	"ID" serial NOT NULL,
	"ID_point" integer NOT NULL,
	"Mark" integer NOT NULL,
	"Phone_client" varchar(255) NOT NULL,
	"Comment" varchar(255) NOT NULL,
	CONSTRAINT "FEEDBACK_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);



CREATE TABLE "POINT" (
	"ID" serial NOT NULL,
	Address serial NOT NULL,
	"Max_number_order" integer NOT NULL,
	"Phone" integer NOT NULL,
	CONSTRAINT "POINT_pk" PRIMARY KEY ("ID")
) WITH (
  OIDS=FALSE
);




ALTER TABLE "DISH" ADD CONSTRAINT "DISH_fk0" FOREIGN KEY ("ID_group") REFERENCES "GROUPS_DISH"("ID");

ALTER TABLE "ORDER_DISH" ADD CONSTRAINT "ORDER_DISH_fk0" FOREIGN KEY ("ID_order") REFERENCES "ORDER"("ID");
ALTER TABLE "ORDER_DISH" ADD CONSTRAINT "ORDER_DISH_fk1" FOREIGN KEY ("ID_dish") REFERENCES "DISH"("ID");

ALTER TABLE "ORDER" ADD CONSTRAINT "ORDER_fk0" FOREIGN KEY ("ID_type") REFERENCES "TYPE_DELIVERY"("ID");
ALTER TABLE "ORDER" ADD CONSTRAINT "ORDER_fk1" FOREIGN KEY ("ID_point") REFERENCES "POINT"("ID");


ALTER TABLE "FEEDBACK" ADD CONSTRAINT "FEEDBACK_fk0" FOREIGN KEY ("ID_point") REFERENCES "ORDER"("ID");


