CREATE TABLE GROUPS_DISH
(
    ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    Name varchar(255) NOT NULL,
    CONSTRAINT GROUPS_DISH_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );



CREATE TABLE DISH
(
    ID       INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    Name     varchar(255) NOT NULL,
    Price    integer      NOT NULL,
    ID_group integer      NOT NULL,
    CONSTRAINT DISH_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );



CREATE TABLE ORDER_DISH
(
    ID_order INTEGER,
    ID_dish  INTEGER,
    Count    integer
) WITH (
      OIDS = FALSE
      );



CREATE TABLE "order"
(
    ID          INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_customer integer NOT NULL,
    ID_type     integer NOT NULL,
    ID_point    integer NOT NULL,
    CONSTRAINT ORDER_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );



CREATE TABLE TYPE_DELIVERY
(
    ID   INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    Name varchar(255) NOT NULL,
    CONSTRAINT TYPE_DELIVERY_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );



CREATE TABLE FEEDBACK
(
    ID       INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    ID_order INTEGER      NOT NULL,
    Mark     integer      NOT NULL,
    Comment  varchar(255) NOT NULL,
    CONSTRAINT FEEDBACK_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );



CREATE TABLE POINT
(
    ID     INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    Adress varchar(255) NOT NULL,
    Phone  varchar(10)  NOT NULL,
    CONSTRAINT POINT_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );

Create Table CUSTOMER
(
    ID      INTEGER      NOT NULL GENERATED ALWAYS AS IDENTITY,
    Phone   varchar(255) NOT NULL,
    key     varchar,
    iv      varchar,
    ID_USER INTEGER,
    ID_ROLE INTEGER,
    CONSTRAINT CUSTOMER_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );

Create Table "user"
(
    ID   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    hash varchar,
    CONSTRAINT user_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );

Create Table ROLE
(
    ID   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME varchar(255),
    CONSTRAINT ROLE_pk PRIMARY KEY (ID)
) WITH (
      OIDS = FALSE
      );

ALTER TABLE CUSTOMER
    ADD CONSTRAINT CUSTOMER_fk0 FOREIGN KEY (ID_USER) REFERENCES "user" (ID);

ALTER TABLE CUSTOMER
    ADD CONSTRAINT CUSTOMER_fk1 FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID);


ALTER TABLE DISH
    ADD CONSTRAINT DISH_fk0 FOREIGN KEY (ID_group) REFERENCES GROUPS_DISH (ID);

ALTER TABLE ORDER_DISH
    ADD CONSTRAINT ORDER_DISH_fk0 FOREIGN KEY (ID_order) REFERENCES "order" (ID);
ALTER TABLE ORDER_DISH
    ADD CONSTRAINT ORDER_DISH_fk1 FOREIGN KEY (ID_dish) REFERENCES DISH (ID);

ALTER TABLE "order"
    ADD CONSTRAINT ORDER_fk0 FOREIGN KEY (ID_type) REFERENCES TYPE_DELIVERY (ID);
ALTER TABLE "order"
    ADD CONSTRAINT ORDER_fk1 FOREIGN KEY (ID_point) REFERENCES POINT (ID);
ALTER TABLE "order"
    ADD CONSTRAINT ORDER_fk2 FOREIGN KEY (ID_customer) REFERENCES CUSTOMER (ID);

ALTER TABLE FEEDBACK
    ADD CONSTRAINT FEEDBACK_fk0 FOREIGN KEY (ID_order) REFERENCES "order" (ID);


